# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/WorkBORI/Basys-3/hw/src/constraints/Basys3_Master.xdc

# IP: D:/WorkBORI/Basys-3/hw/src/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet
