# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache X:/EC551/FinalProject/Nexys7/vivado_proj/.Xil/Vivado-23064-ECE-PHO115-15/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir X:/EC551/FinalProject/Nexys7/vivado_proj/Nexys-A7-100T-XADC.cache/wt [current_project]
set_property parent.project_path X:/EC551/FinalProject/Nexys7/vivado_proj/Nexys-A7-100T-XADC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {X:/EC551/FinalProject/Nexys7/vivado_proj/Nexys-A7-100T-XADC.board} [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_repo_paths x:/repo [current_project]
update_ip_catalog
set_property ip_output_repo x:/EC551/FinalProject/Nexys7/vivado_proj/Nexys-A7-100T-XADC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/bg_gen.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/clock_divider.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/debounce.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/dec_bcd.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/game.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/increment_one.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/menu_screen.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/num_hex.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/paddle.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/score_to_7seg.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/square.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/sram.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/start_square.v}
  X:/EC551/FinalProject/Nexys7/vivado_proj/Nexys-A7-100T-XADC.srcs/sources_1/imports/hdl/top.v
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/topmodule.v}
  {//ad/eng/users/c/n/cnaught1/My Documents/GitHub/EC551_FinalProject/Pong Game/hdl/vga640x480.v}
  X:/EC551/FinalProject/Nexys7/vivado_proj/Nexys-A7-100T-XADC.srcs/sources_1/new/top_new.v
}
read_ip -quiet X:/EC551/FinalProject/Nexys7/vivado_proj/Nexys-A7-100T-XADC.srcs/xadc_wiz_0/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all x:/EC551/FinalProject/Nexys7/vivado_proj/Nexys-A7-100T-XADC.srcs/xadc_wiz_0/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all x:/EC551/FinalProject/Nexys7/vivado_proj/Nexys-A7-100T-XADC.srcs/xadc_wiz_0/ip/xadc_wiz_0/xadc_wiz_0.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc X:/EC551/FinalProject/Nexys7/vivado_proj/Nexys-A7-100T-XADC.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files X:/EC551/FinalProject/Nexys7/vivado_proj/Nexys-A7-100T-XADC.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_new -part xc7a100tcsg324-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_new.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_new_utilization_synth.rpt -pb top_new_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
