# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/proj/Nexys-A7-100T-XADC.cache/wt [current_project]
set_property parent.project_path D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/proj/Nexys-A7-100T-XADC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths D:/Github/vivado-boards/new/board_files [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_repo_paths d:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/repo [current_project]
set_property ip_output_repo d:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/repo/cache [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/hdl/DigitToSeg.v
  D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/hdl/counter3bit.v
  D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/hdl/decoder3_8.v
  D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/hdl/mux4_4bus.v
  D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/hdl/segClkDevider.v
  D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/hdl/sevensegdecoder.v
  D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/hdl/top.v
}
read_ip -quiet D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/ip/xadc_wiz_0/xadc_wiz_0.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/constraints/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files D:/Github/prerelease/Nexys-A7/Nexys-A7-100T-XADC/src/constraints/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top XADCdemo -part xc7a100tcsg324-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef XADCdemo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file XADCdemo_utilization_synth.rpt -pb XADCdemo_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
